version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstal:
    - location: webapp/codedeploy/stop_server.sh
      runas: root
      timeout: 180
  AfterInstall:
    - location: webapp/codedeploy/afterInstall.sh
      runas: root
      timeout: 180
  ApplicationStart:
    - location: webapp/codedeploy/start_server.sh
      timeout: 3600
      runas: root