version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: codedeploy/afterInstall.sh
      runas: ubuntu
      timeout: 180
  ApplicationStart:
    - location: codedeploy/start_server.sh
      timeout: 3600
      runas: ubuntu