---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            echo "Hello World"
  build:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: Running builds
          command: |
            echo "Hello World"


workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
  build-deploy-workflow:
    jobs:
      - build



# version: 2.1
# jobs:
#   build:
#     docker: 
#       - image: circleci/node:8.10.0 # the primary container, where your job's commands are run
#     steps:
#       - checkout # check out the code in the project directory
#       - run: echo "hello world"